# Setup
title:               Scourge and the Sweeps
tagline:             ''
description:         ''
url:                 https://scourgethetracker.github.io
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Scourge the Tracker
  url:
  email:             scourgethetracker@proton.me

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
