# Setup
title:               Scourge and the Sweeps
tagline:             ''
description:         ''
url:                 https://scourgethetracker.github.io
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Scourge the Tracker
  url:               https://scourgethetracker.github.io
  email:             scourgethetracker@proton.me

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:            0.99
